# Generated by Django 5.2.3 on 2025-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
