# Generated by Django 5.2.3 on 2025-07-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_ban_users', 'Can ban or unban users')]},
        ),
    ]
