# Generated by Django 5.2.3 on 2025-06-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='posted_at',
        ),
    ]
