# Generated by Django 5.2.3 on 2025-07-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
