# Generated by Django 5.2.3 on 2025-07-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='friends', max_length=10),
        ),
    ]
